spring:
  profiles:
    default: local
  jackson:
    time-zone: Asia/Seoul
    default-property-inclusion: non_null
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret: ${JWT_SECRET_KEY}
  access-expiration: 30m
  refresh-expiration: 14d

cookie:
  domain: ${COOKIE_DOMAIN:localhost}
  secure: ${COOKIE_SECURE:true}
  same-site: ${COOKIE_SAME_SITE:Lax}

mail:
  from: ${MAIL_FROM:no-reply@harucut.com}